services:
    portfolio:
        container_name: portfolio
        build:
            context: .
            dockerfile: dev.Dockerfile
        ports:
            - "${DEV_PORT}:3000"
        environment:
            - NEXT_PUBLIC_AUTHOR="${NEXT_PUBLIC_AUTHOR}"    
        volumes:
            - ./website/src:/app/src
            - ./website/tailwind.config.js:/app/tailwind.config.js